#!/bin/bash
confini="/etc/tab/conf/default.ini"
IPOK="no"

get_settings () {
  echo "Loading settings ..."
  source $confini
}

save_settings () {
  echo "Saving settings ..."
  crudini --ini-options=nospace --set $confini "" scriptver \"$scriptver\"
  crudini --ini-options=nospace --set $confini "" veeamxfs \"$veeamxfs\"
  crudini --ini-options=nospace --set $confini "" webmin \"$webmin\"
  crudini --ini-options=nospace --set $confini "" docker \"$docker\"
  crudini --ini-options=nospace --set $confini "" vupw \"$vupw\"
  crudini --ini-options=nospace --set $confini "" devnm \"$devnm\"
  crudini --ini-options=nospace --set $confini "" nasip \"$nasip\"
  crudini --ini-options=nospace --set $confini "" host \"$host\"
  crudini --ini-options=nospace --set $confini "" uuid \"$uuid\"
  crudini --ini-options=nospace --set $confini "" initiator \"$initiator\"
  crudini --ini-options=nospace --set $confini "" mountpoint \"$mountpoint\"
  crudini --ini-options=nospace --set $confini "" tapw \"$tapw\"
  crudini --ini-options=nospace --set $confini "" lturl \"$lturl\"
  crudini --ini-options=nospace --set $confini "" serverip \"$serverip\"
  crudini --ini-options=nospace --set $confini "" iscsifail \"$iscsifail\"
  crudini --ini-options=nospace --set $confini "" rebooted \"$rebooted\"
  crudini --ini-options=nospace --set $confini "" setup_cron \"$setup_cron\"
  crudini --ini-options=nospace --set $confini "" update_os \"$update_os\"
  crudini --ini-options=nospace --set $confini "" install_webmin \"$install_webmin\"
  crudini --ini-options=nospace --set $confini "" install_docker \"$install_docker\"
  crudini --ini-options=nospace --set $confini "" set_ip \"$set_ip\"
  crudini --ini-options=nospace --set $confini "" tabadmin_pw \"$tabadmin_pw\"
  crudini --ini-options=nospace --set $confini "" set_nasip \"$set_nasip\"
  crudini --ini-options=nospace --set $confini "" set_initiator \"$set_initiator\"
  crudini --ini-options=nospace --set $confini "" iscsi_conf \"$iscsi_conf\"
  crudini --ini-options=nospace --set $confini "" set_uuid \"$set_uuid\"
  crudini --ini-options=nospace --set $confini "" veeam_user \"$veeam_user\"
  crudini --ini-options=nospace --set $confini "" veeam_perms \"$veeam_perms\"
  crudini --ini-options=nospace --set $confini "" lt_installed \"$lt_installed\"
  crudini --ini-options=nospace --set $confini "" fstab_updated \"$fstab_updated\"
  crudini --ini-options=nospace --set $confini "" iscsi_edited \"$iscsi_edited\"
  crudini --ini-options=nospace --set $confini "" partitioned \"$partitioned\"  
}

keystroke () {
  echo
  echo "Press any key to continue ..."
  read -rsn1
}

function checkCidrFormat {
  IPOK="no"
  local ipCidr="${1}"
  local validIpCidr
  validIpCidr='(^([1-9]|[1-9][0-9]|[1][0-9][0-9]|[2][0-4][0-9]|[2][5][0-5])\.([0-9]|[1-9][0-9]|[1][0-9][0-9]|[2][0-4][0-9]|[2][5][0-5])\.([0-9]|[1-9][0-9]|[1][0-9][0-9]|[2][0-4][0-9]|[2][5][0-5])\.([0-9]|[1-9][0-9]|[1][0-9][0-9]|[2][0-4][0-9]|[2][5][0-5])\/([1-9]|[1-2][0-9]|[3][0-2]))$'
  if [[ $ipCidr =~ ^$validIpCidr ]]; then
    echo "Format valid"
    IPOK="yes"
    return 0
  else
    echo "Not a CIDR format"
    return 1
  fi
}

function checkIPFormat {
  IPOK="no"
  local ipCidr="${1}"
  local validIpCidr
  validIpCidr='(^([1-9]|[1-9][0-9]|[1][0-9][0-9]|[2][0-4][0-9]|[2][5][0-5])\.([0-9]|[1-9][0-9]|[1][0-9][0-9]|[2][0-4][0-9]|[2][5][0-5])\.([0-9]|[1-9][0-9]|[1][0-9][0-9]|[2][0-4][0-9]|[2][5][0-5])\.([0-9]|[1-9][0-9]|[1][0-9][0-9]|[2][0-4][0-9]|[2][5][0-5]))$'
  if [[ $ipCidr =~ ^$validIpCidr ]]; then
    echo "Format valid"
    IPOK="yes"
    return 0
  else
    echo "Not a CIDR format"
    return 1
  fi
}

get_settings
while :
do
    clear
    cat<<EOF
  *** WARNING: If you don't know what you are doing, please do not edit this file! ***
  
  VM Config File Editor $scriptver
  =============================
  [TOGGLE VALLUES - Letter changes value to its other options]
  a. VeeamXFS Server: $veeamxfs
  b. Install WebMin: $webmin
  c. Install Docker: $docker
  d. iSCSI Test Failed: $iscsifail
  e. iSCSI Test Fail Reboot: $rebooted
  f. STAGE: CRON Adjusted: $setup_cron
  g. STAGE: OS Updated: $update_os
  h. STAGE: WebMin Installed: $install_webmin
  i. STAGE: Docker Installed: $install_docker
  j. STAGE: Server IP Set: $set_ip
  k. STAGE: Tabadmin Password Change: $tabadmin_pw
  l. STAGE: NAS IP Set: $set_nasip
  m. STAGE: Intiator Set: $set_initiator
  n. STAGE: iSCSI Configuration Done: $iscsi_conf
  o. STAGE: UUID Set: $set_uuid
  p. STAGE: Veeam User Created: $veeam_user
  q. STAGE: iSCSI Permissions Set: $veeam_perms
  r. STAGE: Automate Instakked: $lt_installed
  s. STAGE: FStab Updated: $fstab_updated
  t. STAGE: iSCSI Partitioned: $partitioned
  u. STAGE: iSCSI Config File Edited: $iscsi_edited

  [MANUAL SETTINGS]
  1. Veeam User Passsword: $vupw
  2. iSCSI Device: $devnm
  3. NAS IP: $nasip
  4. Parent Hostname: $host
  5. Volume UUID: $uuid
  6. iSCSI Initiator: $initiator
  7. Tabadmin Password: $tapw
  8. Automate Agent URL: $lturl
  9. Server IP: $serverip
  0. XFS Mount Point: $mountpoint

  !. Save and exit
  ^. Exit, no save
  $. Script version

EOF
    read -n1 -s menu
    menu="${menu,,}"
    case "$menu" in
    "a") if [ $veeamxfs == "yes" ] ; then veeamxfs="no"
         else veeamxfs="yes"
         fi ;; 
    "b") if [ $webmin == "yes" ] ; then webmin="no"
         else webmin="yes"
         fi ;;     
    "c") if [ $docker == "yes" ] ; then docker="no"
         else docker="yes"
         fi ;;     
    "d") if [ $iscsifail == "yes" ] ; then iscsifail="no"
         else iscsifail="yes"
         fi ;;     
    "e") if [ $rebooted == "yes" ] ; then rebooted="no"
         else rebooted="yes"
         fi ;;     
    "f") if [ $setup_cron == "yes" ] ; then setup_cron="no"
         else setup_cron="yes"
         fi ;;   
    "g") if [ $update_os == "yes" ] ; then update_os="done"
         else update_os="yes"
         fi ;;     
    "h") if [ $install_webmin == "yes" ] ; then install_webmin="done"
         else install_webmin="yes"
         fi ;;     
    "i") if [ $install_docker == "yes" ] ; then install_docker="done"
         else install_docker="yes"
         fi ;;     
    "j") if [ $set_ip == "yes" ] ; then set_ip="done"
         else set_ip="yes"
         fi ;;     
    "k") if [ $tabadmin_pw == "yes" ] ; then tabadmin_pw="done"
         else tabadmin_pw="yes"
         fi ;;     
    "l") if [ $set_nasip == "yes" ] ; then set_nasip="done"
         else set_nasip="yes"
         fi ;;     
    "m") if [ $set_initiator == "yes" ] ; then set_initiator="done"
         else set_initiator="yes"
         fi ;;     
    "n") if [ $iscsi_conf == "yes" ] ; then iscsi_conf="done"
         else iscsi_conf="yes"
         fi ;;     
    "o") if [ $set_uuid == "yes" ] ; then set_uuid="done"
         else set_uuid="yes"
         fi ;;     
    "p") if [ $veeam_user == "yes" ] ; then veeam_user="done"
         else veeam_user="yes"
         fi ;;     
    "q") if [ $veeam_perms == "yes" ] ; then veeam_perms="done"
         else veeam_perms="yes"
         fi ;;     
    "r") if [ $lt_installed == "yes" ] ; then lt_installed="done"
         else lt_installed="yes"
         fi ;;     
    "s") if [ $fstab_updated == "yes" ] ; then fstab_updated="done"
         else fstab_updated="yes"
         fi ;;     
    "t") if [ $partitioned == "yes" ] ; then partitioned="done"
         else partitioned="yes"
         fi ;;     
    "u") if [ $iscsi_edited == "yes" ] ; then iscsi_edited="done"
         else iscsi_edited="yes"
         fi ;;     
    "1") read -p "new veeamuser password: " vupw ;;
    "2") read -p "new device id: " devnm ;;
    "3") echo
         echo "changing this does not re-do the iSCSI settings!"
         read -p "new NAS IP: " nasip ;; # update this to verify this is an IP entered
    "4") read -p "hv host name: " host ;;
    "5") echo
         echo "changing this does not change the FSTAB info!"
         read -p "new UUID: " uuid ;;
    "6") read -p "new initiator: " initiator ;;
    "7") read -p "new tabadmin password: " tapw ;;
    "8") read -p "new agent URL: " lturl ;;
    "9") echo
         echo "changing this does not re-ip the server!"
         echo "Enter the IP in CIDR format. IE, 192.168.1.123/24"
            while [[ $IPOK == "no" ]] ;
              do
              read -rp "new IP: " serverip
              if checkCidrFormat "${serverip}"; then
              echo "Moving on..."
              fi
            done 
            IPOK="no" ;;
    "0") read -p "new agent URL: " lturl ;;
    "!") save_settings
         clear
         exit ;;
    "^") clear
         exit ;;
    * ) echo "Invalid option"
        keystroke ;;
    esac
#    sleep 1
done
